name: watch_communication_plugin_example
description: Demonstrates how to use the watch_communication plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.6"


dependencies:
  flutter:
    sdk: flutter

  watch_communication_plugin: 
    path: ../ 
  cupertino_icons: ^1.0.0
  crypto: any
  device_info: any  
  fluwx: 2.6.2 
  mzanalytics_mybmw: 0.5.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter: 
  uses-material-design: true
 